version: "3.0"
services:
  nagios:
    image: manios/nagios:latest
    ports:
      - "8080:80"
    volumes:
      - ./hello-nagios/etc/:/opt/nagios/etc/
      - ./hello-nagios/var/:/opt/nagios/var/
  #    - ./hello-nagios/ssmtp.conf:/etc/ssmtp/ssmtp.conf
      - ./hello-nagios/custom-plugins/:/opt/Custom-Nagios-Plugins/
    environment:
      - "NAGIOSADMIN_USER=nagiosadmin"
      - "NAGIOSADMIN_PASS=patata"
      - "TZ=Europe/Madrid"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "9025:8025"
